# Generated by Django 4.2.7 on 2025-09-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_app_approved_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='absence',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_app_reported_absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='makeupsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_app_approved_makeups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='makeupsession',
            name='new_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_app_makeup_sessions', to='core.room'),
        ),
        migrations.AlterField(
            model_name='makeupsession',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_app_requested_makeups', to=settings.AUTH_USER_MODEL),
        ),
    ]
